#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

TARGET_DIR="/home/pi/robot-futbol-league"
LOGS_DIR=$TARGET_DIR/logs


exec 1>$LOGS_DIR/rc.local.log 2>&1  # send stdout and stderr from rc.local to a log file
set -x

echo "player-bot started from rc.local" >> $LOGS_DIR/player-bot.log
cd $TARGET_DIR
python3 player-bot/player-bot.py >> $LOGS_DIR/player-bot.log 2>&1

exit 0
